// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: xmtpv4/message_api/notification_api.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// Full envelope stream for notification services.
public protocol Xmtp_Xmtpv4_MessageApi_NotificationApiClientInterface: Sendable {

    func `subscribeAllEnvelopes`(headers: Connect.Headers, onResult: @escaping @Sendable (Connect.StreamResult<Xmtp_Xmtpv4_MessageApi_SubscribeEnvelopesResponse>) -> Void) -> any Connect.ServerOnlyStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeAllEnvelopesRequest>

    @available(iOS 13, *)
    func `subscribeAllEnvelopes`(headers: Connect.Headers) -> any Connect.ServerOnlyAsyncStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeAllEnvelopesRequest, Xmtp_Xmtpv4_MessageApi_SubscribeEnvelopesResponse>
}

/// Concrete implementation of `Xmtp_Xmtpv4_MessageApi_NotificationApiClientInterface`.
public final class Xmtp_Xmtpv4_MessageApi_NotificationApiClient: Xmtp_Xmtpv4_MessageApi_NotificationApiClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    public func `subscribeAllEnvelopes`(headers: Connect.Headers = [:], onResult: @escaping @Sendable (Connect.StreamResult<Xmtp_Xmtpv4_MessageApi_SubscribeEnvelopesResponse>) -> Void) -> any Connect.ServerOnlyStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeAllEnvelopesRequest> {
        return self.client.serverOnlyStream(path: "/xmtp.xmtpv4.message_api.NotificationApi/SubscribeAllEnvelopes", headers: headers, onResult: onResult)
    }

    @available(iOS 13, *)
    public func `subscribeAllEnvelopes`(headers: Connect.Headers = [:]) -> any Connect.ServerOnlyAsyncStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeAllEnvelopesRequest, Xmtp_Xmtpv4_MessageApi_SubscribeEnvelopesResponse> {
        return self.client.serverOnlyStream(path: "/xmtp.xmtpv4.message_api.NotificationApi/SubscribeAllEnvelopes", headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let subscribeAllEnvelopes = Connect.MethodSpec(name: "SubscribeAllEnvelopes", service: "xmtp.xmtpv4.message_api.NotificationApi", type: .serverStream)
        }
    }
}
