// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: xmtpv4/message_api/publish_api.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// Gateway -> Node.
public protocol Xmtp_Xmtpv4_MessageApi_PublishApiClientInterface: Sendable {

    @discardableResult
    func `publishPayerEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `publishPayerEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesRequest, headers: Connect.Headers) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesResponse>
}

/// Concrete implementation of `Xmtp_Xmtpv4_MessageApi_PublishApiClientInterface`.
public final class Xmtp_Xmtpv4_MessageApi_PublishApiClient: Xmtp_Xmtpv4_MessageApi_PublishApiClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `publishPayerEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/xmtp.xmtpv4.message_api.PublishApi/PublishPayerEnvelopes", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `publishPayerEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_PublishPayerEnvelopesResponse> {
        return await self.client.unary(path: "/xmtp.xmtpv4.message_api.PublishApi/PublishPayerEnvelopes", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let publishPayerEnvelopes = Connect.MethodSpec(name: "PublishPayerEnvelopes", service: "xmtp.xmtpv4.message_api.PublishApi", type: .unary)
        }
    }
}
