// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: xmtpv4/message_api/query_api.proto
//

import Connect
import Foundation
import SwiftProtobuf

/// Client -> Node. No auth token required.
public protocol Xmtp_Xmtpv4_MessageApi_QueryApiClientInterface: Sendable {

    @discardableResult
    func `queryEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_QueryEnvelopesRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_QueryEnvelopesResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `queryEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_QueryEnvelopesRequest, headers: Connect.Headers) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_QueryEnvelopesResponse>

    func `subscribeTopics`(headers: Connect.Headers, onResult: @escaping @Sendable (Connect.StreamResult<Xmtp_Xmtpv4_MessageApi_SubscribeTopicsResponse>) -> Void) -> any Connect.ServerOnlyStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeTopicsRequest>

    @available(iOS 13, *)
    func `subscribeTopics`(headers: Connect.Headers) -> any Connect.ServerOnlyAsyncStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeTopicsRequest, Xmtp_Xmtpv4_MessageApi_SubscribeTopicsResponse>

    @discardableResult
    func `getInboxIds`(request: Xmtp_Xmtpv4_MessageApi_GetInboxIdsRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetInboxIdsResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `getInboxIds`(request: Xmtp_Xmtpv4_MessageApi_GetInboxIdsRequest, headers: Connect.Headers) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetInboxIdsResponse>

    @discardableResult
    func `getNewestEnvelope`(request: Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeRequest, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeResponse>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `getNewestEnvelope`(request: Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeRequest, headers: Connect.Headers) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeResponse>
}

/// Concrete implementation of `Xmtp_Xmtpv4_MessageApi_QueryApiClientInterface`.
public final class Xmtp_Xmtpv4_MessageApi_QueryApiClient: Xmtp_Xmtpv4_MessageApi_QueryApiClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `queryEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_QueryEnvelopesRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_QueryEnvelopesResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/xmtp.xmtpv4.message_api.QueryApi/QueryEnvelopes", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `queryEnvelopes`(request: Xmtp_Xmtpv4_MessageApi_QueryEnvelopesRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_QueryEnvelopesResponse> {
        return await self.client.unary(path: "/xmtp.xmtpv4.message_api.QueryApi/QueryEnvelopes", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public func `subscribeTopics`(headers: Connect.Headers = [:], onResult: @escaping @Sendable (Connect.StreamResult<Xmtp_Xmtpv4_MessageApi_SubscribeTopicsResponse>) -> Void) -> any Connect.ServerOnlyStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeTopicsRequest> {
        return self.client.serverOnlyStream(path: "/xmtp.xmtpv4.message_api.QueryApi/SubscribeTopics", headers: headers, onResult: onResult)
    }

    @available(iOS 13, *)
    public func `subscribeTopics`(headers: Connect.Headers = [:]) -> any Connect.ServerOnlyAsyncStreamInterface<Xmtp_Xmtpv4_MessageApi_SubscribeTopicsRequest, Xmtp_Xmtpv4_MessageApi_SubscribeTopicsResponse> {
        return self.client.serverOnlyStream(path: "/xmtp.xmtpv4.message_api.QueryApi/SubscribeTopics", headers: headers)
    }

    @discardableResult
    public func `getInboxIds`(request: Xmtp_Xmtpv4_MessageApi_GetInboxIdsRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetInboxIdsResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/xmtp.xmtpv4.message_api.QueryApi/GetInboxIds", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `getInboxIds`(request: Xmtp_Xmtpv4_MessageApi_GetInboxIdsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetInboxIdsResponse> {
        return await self.client.unary(path: "/xmtp.xmtpv4.message_api.QueryApi/GetInboxIds", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @discardableResult
    public func `getNewestEnvelope`(request: Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeRequest, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeResponse>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/xmtp.xmtpv4.message_api.QueryApi/GetNewestEnvelope", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `getNewestEnvelope`(request: Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Xmtp_Xmtpv4_MessageApi_GetNewestEnvelopeResponse> {
        return await self.client.unary(path: "/xmtp.xmtpv4.message_api.QueryApi/GetNewestEnvelope", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let queryEnvelopes = Connect.MethodSpec(name: "QueryEnvelopes", service: "xmtp.xmtpv4.message_api.QueryApi", type: .unary)
            public static let subscribeTopics = Connect.MethodSpec(name: "SubscribeTopics", service: "xmtp.xmtpv4.message_api.QueryApi", type: .serverStream)
            public static let getInboxIds = Connect.MethodSpec(name: "GetInboxIds", service: "xmtp.xmtpv4.message_api.QueryApi", type: .unary)
            public static let getNewestEnvelope = Connect.MethodSpec(name: "GetNewestEnvelope", service: "xmtp.xmtpv4.message_api.QueryApi", type: .unary)
        }
    }
}
