version: "2"
linters:
  default: "standard"
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - nakedret
    - nilerr

  exclusions:
    rules:
      - linters:
          - staticcheck
        text: SA5008
