#!/bin/bash
set -eou pipefail

set -e

if [ -n "$(go env GOBIN)" ]; then
    FOUND_GOBIN=$(go env GOBIN)
    export PATH="${FOUND_GOBIN}:${PATH}"
fi

if [ -n "$(go env GOPATH)" ]; then 
    FOUND_GOPATH=$(go env GOPATH)
    export PATH="${FOUND_GOPATH}/bin:${PATH}"
fi

PROTO_PATH="${1:-buf.build/xmtp/proto}"

rm -rf ./pkg/proto
buf generate --template proto/buf.gen.yaml
buf generate "$PROTO_PATH"